### ISSUE TITLE
direnv support

### ISSUE THREAD

**Issue by blaggacao** [jlesquembre/kubeprompt#12]
```shell
# .envrc
export KUBECONFIG=$(kubeprompt)
```

Just need to detect the go equivalent of:

```bash
        if [[ ''${DIRENV_IN_ENVRC:-} = 1 ]]; then
          return $TMPFILE
        fi
```

This is useful if a projects subfolder should scope to different environments.

A common use case is having kustomize overlays for:

```shell
├── bases
└── overlays
    ├── dev
    ├── prod
    └── staging
```

```shell
# ./overlays/dev/.envrc
kubectl config use-context k3d-local
export KUBECONFIG=$(kubeprompt)
```

**Comment by jlesquembre** [comment]
I created a first version, there is some documentation here:
https://github.com/jlesquembre/kubeprompt/tree/direnv#usage-with-direnv

Let me know if something is not clear or if you see room for improvement. If not, I think I'll play with it, and unless I find issued, I'll cut a new release.

BTW, I also use kustomize, my project layout looks the same

**Comment by blaggacao** [comment]
Super! Nice, will check it out. But looks good!
