### ISSUE TITLE
Aurora greedily consumes chars in zsh prompt

### ISSUE THREAD

**Issue by blaggacao** [jlesquembre/kubeprompt#13]
It happens o that zsh seems to require special escapes so that color escape codes do not consume caracters in the tty:

https://github.com/jonmosco/kube-ps1/blob/486404e4b19b009ed0caaa55f642307ce8f3a506/kube-ps1.sh#L57-L73

![image](https://user-images.githubusercontent.com/7548295/94513015-3b5bad80-01e3-11eb-9a84-9f4d9250ad40.png)

**_Problem: I tried to work around working with the formatting context, but that doesn't work reliably since in `direnv` and `shellHook` the shell is always `bash` and _not_ the end user shell. So I can't detect the end user shell in my setup._**

I opened https://github.com/numtide/devshell/issues/25 to track discussion on this user shell transparency.

**Comment by blaggacao** [comment]
The problem seems to be, that in nix shell evaluation, I haven't found a way to detect the end user shell: it's always bash. That affects `direnv` and `shelHook`

**Comment by jlesquembre** [comment]
I could be wrong, but I think that nix shell evaluation happens in bash, and you cannot use a different shell.
related meme: https://www.reddit.com/r/NixOS/comments/j2bbps/the_dark_secret_of_nixpkgs/

Not sure if there is anything I can do here, seems more a problem to be fixed in Aurora or zsh

**Comment by blaggacao** [comment]
I've opened an issue over there to see if it can be helped: https://github.com/numtide/devshell/issues/25
