### ISSUE TITLE
Explain the difference with "Related tools"

### ISSUE THREAD

**Issue by yngvark** [jlesquembre/kubeprompt#15]
How is kubeprompt different from https://github.com/jonmosco/kube-ps1? Would be nice with a sentence or two explaining the difference, so I don't have to read through the whole readmes of both tools to understand the difference.

I guess the answer is the text in https://github.com/jlesquembre/kubeprompt#why-to-copy-kubeconfig-and-start-a-sub-shell .

**Comment by jlesquembre** [comment]
Some of the "related tools" are complimentary, while others are alternatives. I use some of them in combination with kubeprompt. I don't want to maintain a list of differences with other tools,  but if you have suggestions about how to make the readme clearer, I'll be happy to add them. 

Your guess is right, that's one of the differences. The main difference is that kubeprompt isolates your kubeconfig per terminal. I hoped that the first line in the readme made that clear: Isolates KUBECONFIG in each shell and shows the current Kubernetes context/namespace in your prompt 

The other differences (as of today) with [kube-ps1](https://github.com/jonmosco/kube-ps1) are:
- Developed in golang vs bash
- shell-agnostic vs bash+zsh

**Comment by yngvark** [comment]
> I don't want to maintain a list of differences with other tools

I think the tools' core functionality probably won't change, so my idea was just a sentence or two that quickly explains the main difference, not a big list of differences.

> I hoped that the first line in the readme made that clear

It does, I guess I was a bit too quick when scanning the README. So this might be good enough.
