### ISSUE TITLE
Brew install doesn't work

### ISSUE THREAD

**Issue by dberuben** [jlesquembre/kubeprompt#16]
Hi,

I tried 

```
 brew tap jlesquembre/kubeprompt https://github.com/jlesquembre/kubeprompt/

==> Tapping jlesquembre/kubeprompt
Cloning into '/usr/local/Homebrew/Library/Taps/jlesquembre/homebrew-kubeprompt'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

but it failed so i did
```
 git clone https://github.com/jlesquembre/kubeprompt.git /usr/local/Homebrew/Library/Taps/jlesquembre/homebrew-kubeprompt --origin=origin --template=
 and 
 brew install kubeprompt
 it works
 ```

**Comment by jlesquembre** [comment]
um, not sure why, I don't use brew myself, but according to brew docs: https://docs.brew.sh/Taps
that command should work. Looks like tries to clone `jlesquembre/homebrew-kubeprompt` (instead of `jlesquembre/kubeprompt`)

Are you on latest brew? I just tested it with the docker image (brew version 3.2.0) it worked

**Comment by dberuben** [comment]
Yes, i'm in the very latest version

```
Homebrew 3.2.0
Homebrew/homebrew-core (git revision 58cb669129; last commit 2021-06-28)
Homebrew/homebrew-cask (git revision 739030b388; last commit 2021-06-28)
```

**Comment by jlesquembre** [comment]
no idea why you are getting that error. I cannot reproduce it on linux, and unfortunately, I don't have a mac to test it. I'll try to find a way to reproduce it, but if in the meantime you find anything, let me know.

**Comment by dberuben** [comment]
No idea, maybe MacOS with BigSur?

**Comment by jlesquembre** [comment]
@dberuben I hope you were able to fix the issue
