### ISSUE TITLE
Request for advice: using kubeprompt inside a shell script

### ISSUE THREAD

**Issue by mpartio** [jlesquembre/kubeprompt#17]
Is there a way to call kubeprompt inside a shell script? At least inside a bash script it seems to stop the execution of the script and request input from caller. 

This might a bash thing also and not directly related to kubeprompt?

For example:

```
$ cat kubeprompt-test.bash
kubeprompt
kubeprompt -c

echo "do stuff"

exit # kubeprompt

echo "do other stuff still"

exit # script
```

Running the script

```
$ bash -x kubeprompt-test.bash 
+ kubeprompt
$ exit                   <<------- script execution stopped before this line; I typed 'exit' here manually
+ kubeprompt -c
kubeprompt is NOT active
+ echo 'do stuff'
do stuff
+ exit
```

Thanks!

**Comment by jlesquembre** [comment]
what are you trying to achieve? 

You can call it from a shell script, but keep in mind just calling `kubeprompt` without any flags will start a sub-shell. 

If you want get the information in your script, you can call it like this: `kubeprompt --format "(K8S {{.Ctx | Yellow | Bold}}|{{.Ns | Magenta | Bold}})"`

**Comment by mpartio** [comment]
I need to run a bunch of different kind of scripts through an orchestration tool. Each script does some initialization, then starts jobs to kube cluster. The scripts are run all on the same server and can be run simultaneously, hence the requirement of using kubeprompt.

Currently I cannot call kubeprompt like I described above as the execution of the script stops after calling "kuberprompt" the first time.

**Comment by jlesquembre** [comment]
But why do you need kubeprompt for that? Wouldn't be easier to use kubectl directly?

**Comment by mpartio** [comment]
I'm connecting to different kubernetes-instances and different openshift projects.

For example, simultaneously (in different scripts) I might start job-a to openshift project A and job-b to openshift project B. 

When these are executed on a single server, the global state of kubectl/oc tool will change each time and it becomes a mess.

**Comment by jlesquembre** [comment]
I see, I had a similar problem in the past.
What I'd do, is to copy the kubeconfig to different temp directories, and then set a different KUBECONFIG env variable per script

**Comment by mpartio** [comment]
Interesting idea. This would be actually the same thing as what kubeprompt is doing, but without launching a subshell?

**Comment by jlesquembre** [comment]
yes, basically it would be the same.

I remember that I was working on adding support for `direnv`, but never released it, I think is a good time for it :)

If you update to 0.4.0, you can do:

```
export KUBECONFIG=$(kubeprompt -t)
```

in your script. That will create a copy of your kubeconfig to a temp folder, without launching a sub-shell. After it, the `kubectl` command will use the kubeconfig copy

**Comment by mpartio** [comment]
Thanks! I will try the new version to see how it works.

**Comment by jlesquembre** [comment]
@mpartio I hope you were able to solve your problem, I'm closing this issue, but feel free to ask if you have more questions

**Comment by mpartio** [comment]
Yes the new solution works fine, thanks!
