### ISSUE TITLE
Change context? (bash)

### ISSUE THREAD

**Issue by butuzov** [jlesquembre/kubeprompt#2]
I wonder if it's actually possible to change $PS1 after switching context in bash.

![image](https://user-images.githubusercontent.com/651824/68133731-9cbec200-ff29-11e9-9f7d-2f7aa41737ad.png)

```bash
# Added before declaration of PS1
export KUBECONFIG=~/.kube/config
kubeprompt
```

+ context not changing
+ shell losing all of the nice things, like auto-completion (because of kubeprompt switchover)

/ no bueno =(

**Comment by butuzov** [comment]
Guess I learned something new today!

```bash
kubeprompt_ctx_check(){

    CURRENT_CONTEXT_NOT_SET=$(kubectl config current-context 2>&1 \
        | grep "current-context is not set")

    if [[ ! -z $CURRENT_CONTEXT_NOT_SET ]]; then
        exit 0
    fi
    
    # -m setting is from the forked version of the kubeprompt
    # it maybe not implemented in original code.
    printf " %s " $(kubeprompt -fm)
}

PS1="${RESET}"
PS1+="${WHITE} $ \u ${RESET}"
# adding backslash makes output dynamic, not static.
PS1+="${BLUE}\$(kubeprompt_ctx_check)${RESET}"
PS1+="${GREEN} \w ${RESET}"
PS1+="\n${YELLO} > ${RESET}"
export PS1=$PS1
```

## demo
![image](https://user-images.githubusercontent.com/651824/68138022-8e27d900-ff30-11e9-93fe-914c69aacf3b.png)

**Comment by jlesquembre** [comment]
Is it solved in #4? 
btw, I think you don't need the `kubeprompt_ctx_check` check, if you don't want to print anything in case kubeprompt is not enable, you could call `kubeprompt -p`, which it will do nothing if kubeprompt is disabled, I think you can replace
```
PS1+="${BLUE}\$(kubeprompt_ctx_check)${RESET}"
```
with
```
PS1+="${BLUE}\$(kubeprompt -p)${RESET}"
```

**Comment by butuzov** [comment]
Yeah, #4 has instructions on how to correctly enable it.

As for the alternative way to implement it, `kubeprompt -p` complained that it's not active, after activation as I did in #3 - I lost all my autocompletes and custom features, etc etc etc...
`kubeprompt -f` doesn't have such a problem.

**Comment by jlesquembre** [comment]
I think this is solved, feel free to reopen if you not
