### ISSUE TITLE
Activation?

### ISSUE THREAD

**Issue by butuzov** [jlesquembre/kubeprompt#3]
Should `readme` examples include part about pros/cons of `-p` and `-f` options?

And should it also include an example of actual activation with running `kubeprompt` with no options at all (as it spawns new shell).

**Comment by jlesquembre** [comment]
I tried to improve the docs: https://github.com/jlesquembre/kubeprompt/commit/b5ad28dff4e4b73256bbb0552428972dc4775cfb

Is it clearer now?

**Comment by butuzov** [comment]
It’s actually looks awesome! Much much better!

**Comment by jlesquembre** [comment]
Good to hear :-)
Thanks for your feedback
