### ISSUE TITLE
Custom formated string

### ISSUE THREAD

**Issue by butuzov** [jlesquembre/kubeprompt#5]
one more idea is actually to have custom formated string with two strings placeholders something `%s%s`

```bash
>kubeprompt -f --fmt "⎈ %s@%s"
⎈ minikube@default
```

**Comment by jlesquembre** [comment]
That's something I'd like to add, and also make the colors customizable. It is related to #1 , which I'm going to merge, but I'd like to find a more general solution. I'll no be able to look to that in the next days/weeks, if you want to submit a PR is very welcome

**Comment by butuzov** [comment]
I am super interested in this, but the same as you busy a bit. I hope i will find time in the next few weeks too, I am kinda like a project too.

**Comment by butuzov** [comment]
WIP - Simple implementation in #6 

Pros: it's simple.
Cons: what is there no "%s", what if there is only one "%s", how to pass color sequence?

**Comment by butuzov** [comment]
jlesquembre/kubeprompt#7 solve the issue.
