### ISSUE TITLE
Customize prompt with golang templates

### ISSUE THREAD

**Issue by jlesquembre** [jlesquembre/kubeprompt#7]
I'm thinking about customizing the prompt using go templates.
The templates will have access to 3 variables, `Ctx`, `Ns` and `Enabled`, and to the color functions provided by Aurora. I think this solution gives to the users a lot of flexibility, and will allow to remove some of the flags. Some examples:

Default behaviour:
```go
`(k8s {{.Ctx|Yellow}}|{{.Ns|Magenta}})`
```

Monochrome:
```go
`(k8s {{.Ctx}}|{{.Ns}})`
```

Print only if enabled:
```go
`{{if .Enabled}}k8s {{.Ctx}}|{{.Ns}}{{end}}`
```

Print `k8s` with a different color if kubepromt is enabled:
```go
`{{if .Enabled}}{{"k8s"|Green|Bold}}{{else}}{{"k8s"|Red}}{{end}} {{.Ctx}}|{{.Ns}}`
```
ping @butuzov

**Comment by butuzov** [comment]
lgtm

**Comment by jlesquembre** [comment]
Fixed in https://github.com/jlesquembre/kubeprompt/commit/534bea6d65f9c151bca3c1ca94e072e22d131204
