### ISSUE TITLE
Shell substitution.

### ISSUE THREAD

**Issue by butuzov** [jlesquembre/kubeprompt#8]
There are small issues, like shell substitution now.

![image](https://user-images.githubusercontent.com/651824/68751190-d66a8980-0609-11ea-9165-99680f4a9016.png)

any usage of the `kupeprompt`, leave with no my helper functions.

**Comment by jlesquembre** [comment]
`.dots` is an alias, right?
Not sure what is happening, I did a quick test, just created an `alias` in my bashrc, and after starting a subshell, the alias is still there. 
Can you provide a minimal example?

**Comment by butuzov** [comment]
Pretty much anything. It's basically useless, after the first run.

**Comment by jlesquembre** [comment]
how are you loading your aliases? are they in your `~/.bashrc` file? Aliases are not part of the environment, and will not be inherited in the sub-shell

**Comment by butuzov** [comment]
That's bad. I wanted to be informed of the current Kubernetes context while having access to all my snippets. Whats are advantages of current (0.2.0) version approach against having it and using it just as informer?

**Comment by jlesquembre** [comment]
You can still using it just as an informer, without activating it, invoke it with
```
kubeprompt -p -f '(⎈ {{.Ctx}}|{{.Ns}})'
```

Anyways, I'd recommend that you load your aliases and snippets in your `bashrc` file.

Thinking more about it, the `-f` option should make `-p` implicit, making `-f` equal to `-p -f`.

**Comment by butuzov** [comment]
Guess I miss it. 

* `kubeprompt -p -f '(⎈ {{.Ctx}}|{{.Ns}})'` works fine for me
* `kubeprompt -f '(⎈ {{.Ctx}}|{{.Ns}})'` actually breaking stuff. 

but this resolves my issues. ¡gracias!

**Comment by jlesquembre** [comment]
De nada :)
I'm thinking about removing the `-p` option and unify it with `-f` to simplify it

**Comment by jlesquembre** [comment]
@butuzov in the latest version, `0.3.0`, I removed the `-p` option, now `-f` has the same behavior that `-p -f` in the previous version. Now `kubeprompt -f '(⎈ {{.Ctx}}|{{.Ns}})'` should work for you
